// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkuxearospwysmircmsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrdXhlYXJvc3B3eXNtaXJjbXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzEyMTgsImV4cCI6MjA2OTkwNzIxOH0.IhT0NYtqcbdxtNboQLF8CigT3ZoSVHuo1NxT4IOzwKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});